/* Shared project data for homepage lightbox and project detail pages. */
window.MODFORM_PROJECTS = [
  {
    name: 'Jal Villa',
    slug: 'jal-villa',
    category: 'Residential',
    location: 'Alibaug, Maharashtra',
    year: 'Design Study',
    area: '620 sqm',
    status: 'Concept Proposal',
    images: [
      'assets/projects/residence-01.jpeg',
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-03.jpeg',
    ],
    desc: 'Jal Villa explores a waterfront retreat on the Alibaug coastline, designed around monsoon light, cross-ventilation, and calm family living. Interlocking volumes, shaded terraces, and a grounded material palette create a home that feels contemporary without losing its Indian warmth.',
  },
  {
    name: 'Vayu Residence',
    slug: 'vayu-residence',
    category: 'Residential',
    location: 'Mumbai, Maharashtra',
    year: 'Design Study',
    area: '540 sqm',
    status: 'Concept Proposal',
    images: [
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-04.jpeg',
      'assets/projects/residence-05.jpeg',
    ],
    desc: 'Vayu Residence studies a compact urban family home with layered balconies, planting ledges, and carefully controlled privacy. The facade uses warm surfaces, deep reveals, and filtered light to soften the relationship between home and street.',
  },
  {
    name: 'Aranya Courtyard Home',
    slug: 'aranya-courtyard-home',
    category: 'Residential',
    location: 'Bengaluru, Karnataka',
    year: 'Design Study',
    area: '480 sqm',
    status: 'Concept Proposal',
    images: [
      'assets/projects/residence-03.jpeg',
      'assets/projects/residence-01.jpeg',
      'assets/projects/residence-05.jpeg',
    ],
    desc: 'Aranya Courtyard Home is organised around a shaded inner court, bringing daylight, breeze, and a quiet centre into everyday life. The design balances open social spaces with private rooms that remain cool, calm, and connected to greenery.',
  },
  {
    name: 'Haveli Twelve',
    slug: 'haveli-twelve',
    category: 'Residential',
    location: 'Jaipur, Rajasthan',
    year: 'Design Study',
    area: '880 sqm',
    status: 'Concept Proposal',
    images: [
      'assets/projects/residence-04.jpeg',
      'assets/projects/residence-03.jpeg',
      'assets/projects/residence-01.jpeg',
    ],
    desc: 'Haveli Twelve reinterprets the layered movement, shaded thresholds, and crafted screens of a traditional Indian haveli for a contemporary family. The proposal focuses on privacy, climate response, and a memorable arrival sequence.',
  },
  {
    name: 'Riverfront Living',
    slug: 'riverfront-living',
    category: 'Residential',
    location: 'Varanasi, Uttar Pradesh',
    year: 'Design Study',
    area: '710 sqm',
    status: 'Concept Proposal',
    images: [
      'assets/projects/residence-05.jpeg',
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-04.jpeg',
    ],
    desc: 'Riverfront Living imagines a family residence that frames landscape, water, and ritual views while protecting interiors from heat and glare. Outdoor rooms, planted edges, and warm evening lighting shape a serene domestic experience.',
  },
  {
    name: 'Lattice House',
    slug: 'lattice-house',
    category: 'Residential',
    location: 'Hyderabad, Telangana',
    year: 'Design Study',
    area: '520 sqm',
    status: 'Concept Proposal',
    images: [
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-04.jpeg',
      'assets/projects/residence-03.jpeg',
    ],
    desc: 'Lattice House studies a family home shaped by shade, ventilation, and crafted facade depth. A rhythmic screen gives privacy from the street while allowing daylight and breeze to move through the living spaces.',
  },
];
