/* Shared project data for homepage lightbox and project detail pages. */
window.MODFORM_PROJECTS = [
  {
    name: 'Residential Project 01',
    slug: 'residential-project-01',
    category: 'Residential',
    location: '',
    year: 'Concept Study',
    area: '',
    status: 'Concept Study',
    images: [
      'assets/projects/residence-01.jpeg',
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-03.jpeg',
    ],
    desc: 'A residential concept exploring shaded thresholds, monsoon-aware ventilation, and a grounded material palette. Interlocking volumes and quiet terraces shape a contemporary home rooted in Indian warmth.',
  },
  {
    name: 'Residential Project 02',
    slug: 'residential-project-02',
    category: 'Residential',
    location: '',
    year: 'Concept Study',
    area: '',
    status: 'Concept Study',
    images: [
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-04.jpeg',
      'assets/projects/residence-05.jpeg',
    ],
    desc: 'A study in compact urban living — layered balconies, planting ledges, and carefully filtered privacy. Warm surfaces and deep reveals soften the relationship between home and street.',
  },
  {
    name: 'Residential Project 03',
    slug: 'residential-project-03',
    category: 'Residential',
    location: '',
    year: 'Concept Study',
    area: '',
    status: 'Concept Study',
    images: [
      'assets/projects/residence-03.jpeg',
      'assets/projects/residence-01.jpeg',
      'assets/projects/residence-05.jpeg',
    ],
    desc: 'Organised around a shaded inner court, the concept brings daylight, breeze, and a quiet centre into everyday life. Open social spaces and private rooms remain cool, calm, and connected to greenery.',
  },
  {
    name: 'Residential Project 04',
    slug: 'residential-project-04',
    category: 'Residential',
    location: '',
    year: 'Concept Study',
    area: '',
    status: 'Concept Study',
    images: [
      'assets/projects/residence-04.jpeg',
      'assets/projects/residence-03.jpeg',
      'assets/projects/residence-01.jpeg',
    ],
    desc: 'A reinterpretation of layered movement, shaded thresholds, and crafted screens drawn from traditional Indian residential typologies. The proposal centres privacy, climate response, and a memorable arrival sequence.',
  },
  {
    name: 'Residential Project 05',
    slug: 'residential-project-05',
    category: 'Residential',
    location: '',
    year: 'Concept Study',
    area: '',
    status: 'Concept Study',
    images: [
      'assets/projects/residence-05.jpeg',
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-04.jpeg',
    ],
    desc: 'A residential study that frames landscape, water, and ritual views while protecting interiors from heat and glare. Outdoor rooms, planted edges, and warm evening lighting shape a serene domestic experience.',
  },
  {
    name: 'Residential Project 06',
    slug: 'residential-project-06',
    category: 'Residential',
    location: '',
    year: 'Concept Study',
    area: '',
    status: 'Concept Study',
    images: [
      'assets/projects/residence-02.jpeg',
      'assets/projects/residence-04.jpeg',
      'assets/projects/residence-03.jpeg',
    ],
    desc: 'A concept shaped by shade, ventilation, and crafted facade depth. A rhythmic screen gives privacy from the street while allowing daylight and breeze to move through the living spaces.',
  },
];
